Gophermart implementation
madatsci/gophermart pull request #2
Opened 2024-11-09 10:18 UTC by madatsci

2024-11-10 11:31 UTC, Bazys requested changes
1. 4.4% совсем смешно для такой проектной работы, надр поднять хотя бы до 40, тем более в следующих спринтах это будет одним из основных требований.
2. не увидел обработки 429 ошибки и прекращения опроса "черного ящика на это время.
3. есть парочка вопросов

2024-11-10 11:31 UTC, Bazys commented on internal/app/server/middleware/auth.go
> +			} else {
зачем `else` если раньше был `return`

2024-11-10 11:31 UTC, Bazys commented on internal/app/store/database/migrations.go
> +func init() {
Функция `init()` в часто считается плохой практикой по нескольким причинам:
1. **Неявные зависимости**: Функции `init()` выполняются автоматически при импорте пакета, что может привести к неявным зависимостям, которые не очевидны из сигнатур функций. Это может затруднить понимание и сопровождение кода.
2. **Неконтролируемый порядок выполнения**: если в пакете имеется несколько функций `init()`, то порядок их выполнения не контролируется программистом в явном виде. Это может привести к непредсказуемому поведению, если функции имеют побочные эффекты, зависящие друг от друга.
3. **Трудности при тестировании**: Функции `init()` запускаются раньше любого другого кода, что может затруднить тестирование. Вы не можете контролировать, когда и выполняется ли функция `init()` в ваших тестах, что может затруднить создание определенных условий для тестирования.
4. **Проблемы производительности**: если функция `init()` выполняет большой объем работы, она может замедлить время запуска программы. Это может стать проблемой для программ, которым требуется быстрый запуск, например, для инструментов командной строки.
5. **Глобальное состояние**: Функции `init()` часто используются для установки глобального состояния, что может привести к проблемам с параллелизмом и сделать код более сложным для понимания.
Вместо использования `init()` часто лучше использовать явные функции инициализации, которые вызываются из `main()` или из функции, которой необходимо инициализированное состояние. Это позволяет четко определить зависимости и порядок выполнения, а также контролировать, когда и как происходит инициализация.
------
1. [Go: функция init](https://medium.com/golangspec/init-functions-in-go-eac191b3860a) - статья на Medium, в которой подробно рассматривается функция `init()` в Go.
2. [Go: Best Practices for Industrial Programming](https://peter.bourgon.org/go-best-practices-2016/#avoid-global-variables) - Руководство по лучшей практике программирования на Go, в котором рекомендуется избегать глобальных переменных и функций `init()`.

Я понимаю, что в примере к пакету flag используется именно так, но это всего лишь пример.

2024-11-10 11:31 UTC, Bazys commented on internal/app/store/database/store.go
> +func (s *Store) CreateOrder(ctx context.Context, order models.Order) (models.Order, error) {
вот это тот случай, когда можно передавать в функцию `order models.Order` по ссылке и возвращать не надо.

2024-11-10 11:31 UTC, Bazys commented on internal/app/handlers/accounts.go
> +		if err.Error() == "sql: no rows in result set" {
так не рекомендуется проверять на ошибки. есть errors.Is/As ,  а в пакете pqx есть типовые ошибки от постгри

2024-11-14 11:14 UTC, madatsci commented on internal/app/handlers/accounts.go
> +		if err.Error() == "sql: no rows in result set" {
Это мне тоже глаз режет, но я использую bun, который возвращает вот такой Error: https://pkg.go.dev/github.com/uptrace/bun/driver/pgdriver@v1.2.5#Error

И там нет метода, чтобы определить, что это empty result. Только если обертку свою написать)

2024-11-14 13:52 UTC, madatsci commented on internal/app/handlers/accounts.go
> +		if err.Error() == "sql: no rows in result set" {
Даже если использовать pgx driver https://bun.uptrace.dev/postgres/#pgx, все равно возвращается обычная ошибка с текстом

2024-11-25 19:25 UTC, Bazys approved these changes
такой вариант меня устраивает

2024-11-26 09:35 UTC, merged